apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: crossplane-cluster-gcp
  labels:
     service: gke
     creation: crossplane
spec:
  forProvider:
    autocaling:
      enableNodeAutoprovisioning:
        maximum: 15
        minimum: 3
        resourceType: 
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkSelector:
       matchLabels:
           service: vpc 
           creation: crossplane
    subnetworkSelector:
       matchLabels:
           service: subnetwork
           creation: crossplane
    location: us-central1-c #change if required
    ipAllocationPolicy:
      useIpAliases: true
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    defaultMaxPodsConstraint:
       maxPodsPerNode: 110
    networkPolicy:
      enabled: false
    resourceLabels:
       owner: crossplane
  providerConfigRef:
        name: default-gcp
